Level roles
wpi-25/bot pull request #34
Opened 2021-01-17 17:33 UTC by EarlJr53

Sam and I wrote the level roles stuff. Here it be.

2021-01-17 17:34 UTC, i-am-gizm0 commented
Closes #27

2021-01-17 17:37 UTC, i-am-gizm0 requested changes, later dismissed

2021-01-17 17:37 UTC, i-am-gizm0 commented on triggers/triggers/levels.ts
> +                member.roles.add(newRole);
Try pulling this out into `util/levels.ts` and import it from there? It should also run that on every start up to update roles if it fell behind

2021-01-21 14:24 UTC, EarlJr53 commented
As I mentioned in the latest commit, we still need to implement setLevelRoles on startup before we can close #27 / #34 . I wasn't exactly sure how we wanted to do that, so I committed what I had and we can figure that out soon.

2021-01-22 14:39 UTC, EarlJr53 commented
@i-am-gizm0 can we merge this into master for now before we add the on-startup check? And then do that after?

2021-01-22 22:08 UTC, i-am-gizm0 approved these changes

2021-01-22 22:08 UTC, merged